export const CHANGE_MENU_STATE = 'CHANGE_MENU_STATE';
export const ADD_LOCAL_TASK = 'ADD_LOCAL_TASK';
export const DELETE_LOCAL_TASK = 'DELETE_LOCAL_TASK';
export const SET_IMPORTANT_TASK = 'SET_IMPORTANT_TASK';
